const USER_LOADING = "USER_LOADING";
const STOP_USER_LOADING = "STOP_USER_LOADING";

const DATA_LOADING = "DATA_LOADING";
const STOP_DATA_LOADING = "STOP_DATA_LOADING";

const SET_USER = "SET_USER";
const SET_BLOGS = "SET_BLOG";
const SET_ONE_BLOG ="SET_ONE_BLOG"

const USER_ERROR = "USER_ERROR";
const CLEAR_USER_ERROR = "CLEAR_USER_ERROR";
const DATA_ERROR = "DATA_ERROR";
const CLEAR_DATA_ERROR = "CLEAR_DATA_ERROR";

module.exports = { USER_LOADING, STOP_USER_LOADING, DATA_LOADING, STOP_DATA_LOADING, SET_USER, SET_BLOGS, SET_ONE_BLOG, USER_ERROR, CLEAR_USER_ERROR, DATA_ERROR, CLEAR_DATA_ERROR };